### ISSUE TITLE
Lost login state when reload

### ISSUE THREAD

**Issue by brunowego** [mateoKaradza/Crystal-Lexicon#2]
I test your app and at this moment when reload the page, will need login again. You know where is the problem?

**Comment by mateoKaradza** [comment]
Firebase automatically stores the user data into the localStorage, but I have no idea how to retrieve it.
I think that it somehow does it on it's own, but I have to find a way how to trigger it. 

I had funny scenario: if you used the app and logged in successfully, and then later tried to login with wrong info, it would log you into the old account. I fixed it now but it was a proof of a hidden remember me. lol
https://github.com/mateoKaradza/Crystal-Lexicon/commit/59d2de457f2596f18628a5f845a518cd31aca348#diff-19ef658434688d0684de4f2a9a7943a4L20

**Comment by mateoKaradza** [comment]
Got it solved now, upon refreshing it will display login page, but in a moment it logs you in and everything works perfectly. :)
